choco install -y sysinternals
choco install -y ngrok.portable
choco install -y python3
choco install -y fiddler
choco install -y winscp
choco install -y rapidee
choco install -y snoop
choco install -y SourceTree
choco install -y notepadplusplus
